#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
LOGGER="logger -t [iPerf3-Server]"

start_service() {
	local basic_list="enable port options"
	for i in $(echo $basic_list);do
		local eval $i="$(uci_get_by_type iperf3-server 0 $i)"
	done;unset i
	if [ "$enable" == 1 ]
	then
		$LOGGER "Starting iPerf3 Server with Port:$port ..."
		procd_open_instance
    	procd_set_param command $(command -v iperf3) -s -p $port $options
    	procd_set_param respawn
		procd_close_instance
	else
		${LOGGER} "iPerf3 Server Service is now disabled ..."
	fi
}

stop_service() {
	$LOGGER "Stopping iPerf3 Server ..."
}

service_triggers() {
	procd_add_reload_trigger "iperf3-server"
}

uci_get_by_type() {
	local ret=$(uci get iperf3-server.@$1[$2].$3 2>/dev/null)
	echo ${ret:=$4}
}
