#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
LOGGER="logger -t [iPerf3]"

start_service() {
	local enable="$(uci_get_by_type iperf3-server 0 enable)"
	local port="$(uci_get_by_type iperf3-server 0 port)"
	local options="$(uci_get_by_type iperf3-server 0 options)"
	if [ $enable == 1 ]
	then
		$LOGGER "Starting iPerf3 Server with port $port ..."
		procd_open_instance
    	procd_set_param command $(command -v iperf3) -s -p $port $options
    	procd_set_param respawn
		procd_close_instance
	else
		stop_service
	fi
}

uci_get_by_type() {
	local ret=$(uci get iperf3-server.@$1[$2].$3 2>/dev/null)
	echo ${ret:=$4}
}

stop_service() {
	$LOGGER "Stopping iPerf3 Server ..."
	killall iperf3
}

service_triggers() {
	procd_add_reload_trigger "iperf3-server"
}
