# Copyright (C) 2020-2021 Hyy2001X <https://github.com/Hyy2001X>

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for AutoUpdate.sh
LUCI_DEPENDS:=+bash
LUCI_PKGARCH:=all
PKG_VERSION:=1.1
PKG_RELEASE:=20211019

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
