#!/bin/bash /etc/rc.common

START=99

start_instance() {
	local enable proxy forceflash github week minute hour
	config_get_bool enable $1 enable
	config_get github $1 github
	Script="/bin/AutoUpdate.sh"
	Script_Command="bash $Script -u"
	if [[ $enable == 1 ]]; then
		config_get proxy $1 proxy
		config_get forceflash $1 forceflash
		config_get week $1 week
		config_get minute $1 minute
		config_get hour $1 hour
		[[ $week == 7 ]] && week='*'
		[[ $proxy == 1 ]] && Script_Command="$Script_Command -P"
		[[ $forceflash == 1 ]] && Script_Command="$Script_Command -F"
		echo -e "$minute $hour * * $week $Script_Command		## AutoUpdate crontab" >> /etc/crontabs/root
	fi
	/etc/init.d/cron restart
	bash $Script -C $github > /dev/null 2>&1
}

remove_corntask() {
	sed -i '/## AutoUpdate crontab/d' /etc/crontabs/root 2> /dev/null
	/etc/init.d/cron restart
}

stop() {
	remove_corntask
}

start() {
	remove_corntask
	config_load autoupdate
	config_foreach start_instance autoupdate
}

service_triggers() {
	procd_add_reload_trigger "autoupdate"
}
