#!/bin/sh /etc/rc.common

START=98
USE_PROCD=0

start_service() {
	local basic_list="enable logfile"
	local port_list="port address delay extra_options enable_port enable_retry"
	for i in $basic_list
	do
		local eval $i="$(uci_get_by_type natter 0 $i)"
	done ; unset i
	if [ "$enable" == 1 ]
	then
		[ ! -f "$logfile" ] && touch $logfile
		for u in $(seq 0 $(($(uci show natter 2> /dev/null | egrep '@ports\[[0-9]\]+=ports' | wc -l) - 1)))
		do
		{
			for i in $port_list
			do
				eval ${i}=$(uci_get_by_type ports $u $i)
			done ; unset i
			if [ "$enable_port" == 1 ]
			then
				while true
				do
					echo "[$(date '+%Y-%m-%d %H:%M:%S')] sleep $delay ; $(command -v python) /usr/share/natter/natter.py $extra_options $address $port" 2>&1 | tee -a $logfile
					sleep $delay 
					$(command -v python) /usr/share/natter/natter.py $extra_options $address $port 2>&1 | tee -a $logfile
					echo "[$(date '+%Y-%m-%d %H:%M:%S')] Port $port exit ..." 2>&1 | tee -a $logfile
					[ "${enable_retry}" != 1 ] && break
				done
				#procd_open_instance
				#procd_set_param command $(command -v python) /usr/share/natter/natter.py $extra_options $address $port 2>&1 | tee -a $logfile
				#procd_set_param respawn 3600 3 10
				#procd_set_param stdout 1
				#procd_set_param stderr 1
				#procd_close_instance
			fi
			unset enable_port delay address port extra_options enable_retry
		} &
		done ; unset u
	else
		stop_service
	fi
}

stop_service() {
	ps -efww | egrep 'natter.py|/etc/init.d/natter' | grep -v 'grep' | awk '{print $1}' | xargs kill -9
}

service_triggers() {
	procd_add_reload_trigger "natter"
}

uci_get_by_type() {
	local ret=$(uci get natter.@$1[$2].$3 2>/dev/null)
	echo ${ret:=$4}
}
